---
title: "p8105_hw5_dry2115"
author: "Dayoung Yu"
date: 2018-11-09
output: github_document
---


```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(hexbin)
library(patchwork)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

## Problem 1

```{r}
study_data = 
  tibble(file_name = list.files(path = "./data"),
         file_path = str_c("./data/", file_name),
         observations = map(file_path, read_csv)) %>%
  unnest()

  


```

## Problem 2


```{r}
url = "https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"

homicide_data = read_csv(file = url) %>%
  mutate(city_state = str_c(city, state, sep = ", ")) %>%
  group_by(city_state, disposition) %>%
  summarize(n = n()) %>% 
  spread(key = disposition, value = n) %>% 
  janitor::clean_names() %>% 
  mutate(
    total_homicides = sum(closed_by_arrest, closed_without_arrest, open_no_arrest, na.rm = TRUE),
    unsolved_homicides = sum(closed_without_arrest, open_no_arrest, na.rm = TRUE)
  ) %>%
  select(city_state, total_homicides, unsolved_homicides)






```

